export type Listing = {
  id: string;
  name: string;
  address: string;
  timezone: string;
  color: string;
  currency: string;
  bufferDays: number;
  checkoutHour: number;
  cleaningBufferHours: number;
  photoIds: string[];
  ready: boolean;
  version: number;
  hasDoorCode: boolean;
  houseManual: {
    wifi: string;
    checkin: string;
    parking: string;
    washroom: string;
    rules: string;
  };
};
export type Source = {
  id: string;
  listingId: string;
  platform: string;
  status: string;
  lastSyncedAt: string | null;
  lastAttemptAt: string | null;
  nextPollAt: string;
  error: string | null;
  enabled: boolean;
};
export type Booking = {
  id: string;
  listingId: string;
  guestName: string;
  startDate: string;
  endDate: string;
  platform: string;
  status: string;
  kind: string;
  reason: string | null;
  price: number | null;
  currency: string;
  confirmedAt: string;
  conflictWithId: string | null;
  version: number;
};
export type Task = {
  id: string;
  listingId: string;
  bookingId: string | null;
  cleanerId: string | null;
  title: string;
  status: string;
  scheduledAt: string;
  verifyBy: string;
  acceptBy: string | null;
  photoId: string | null;
  codeReleasedAt: string | null;
  note: string;
  version: number;
};
export type Cleaner = {
  id: string;
  name: string;
  listingIds: string[];
  enabled: boolean;
};
export type Rule = {
  id: string;
  listingId: string | null;
  name: string;
  keywords: string[];
  manualField: string | null;
  template: string;
  action: string;
  enabled: boolean;
  priority: number;
  version: number;
};
export type Settings = {
  paused: boolean;
  cleaning: boolean;
  messaging: boolean;
  ai: boolean;
  confidence: number;
  version: number;
};
export type Notice = {
  id: string;
  title: string;
  body: string;
  href: string;
  readAt: string | null;
  createdAt: string;
};
export type WorkspaceData = {
  workspace: { id: string; name: string };
  user: { name: string; role: string };
  listings: Listing[];
  sources: Source[];
  tasks: Task[];
  cleaners: Cleaner[];
  settings: Settings;
  rules: Rule[];
  notifications: Notice[];
  integrations: { platform: string; enabled: boolean }[];
  providers: Record<string, boolean>;
  vapidPublicKey: string | null;
  staleMinutes: number;
};
export type Thread = {
  id: string;
  listingId: string;
  bookingId: string;
  externalId: string;
  platform: string;
  status: string;
  intent: string;
  manual: boolean;
  guestName: string;
  preview: string;
  updatedAt: string;
};
export type Message = {
  id: string;
  body: string;
  sender: string;
  status: string;
  automated: boolean;
  aiConfidence: number | null;
  explanation: string | null;
  sentAt: string | null;
  createdAt: string;
};
export type Conversation = {
  thread: Thread;
  booking: Booking;
  pastStays: number;
  messages: Message[];
};
export type Insights = {
  from: string;
  to: string;
  listings: {
    listingId: string;
    name: string;
    color: string;
    currency: string;
    occupancy: number;
    revenue: number;
    pricedStays: number;
    totalStays: number;
    nights: string[];
  }[];
  sync: { platform: string; checks: number; uptime: number | null }[];
  responseSeconds: number | null;
  responseSamples: number;
  cleaningHours: number | null;
  cleaningSamples: number;
  syncSampleCapped: boolean;
};
export type AuditEntry = {
  id: string;
  actorId: string;
  action: string;
  entity: string;
  entityId: string | null;
  reason: string;
  createdAt: string;
};
export type Job = {
  id: string;
  kind: string;
  entityId: string;
  status: string;
  automated: boolean;
  category: string;
  attempts: number;
  error: string | null;
  createdAt: string;
};
